- .github/workflows/sonarscan.yml
- pom.xml
- server/wfprev-api/mvn_settings/settings.xml
- sonar-project.properties
Temporarily uncommenting terraform folder for sonar coverage as it does not exist yet.
> WFPREV-34 Sonar config for Github

- client/wfprev-war/src/main/angular/src/app/components/shared-layout/app-header/app-header.component.html
- client/wfprev-war/src/main/angular/src/styles.scss
> add styling for log out menu (#280)

- .github/workflows/mvn-build.yml
- server/wfprev-api/Dockerfile.graalvm
- server/wfprev-api/pom.xml
- server/wfprev-api/run_docker_build_local.sh
Also added a .sh script to help with running in dev.
> WFPREV-133 - Hooking up the build to use Graalvm.

- README.md
- client/wfprev-war/src/main/angular/src/app/app.component.html
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.ts
- client/wfprev-war/src/main/angular/src/app/components/models.ts
- client/wfprev-war/src/main/angular/src/app/services/project-services.ts
- client/wfprev-war/src/main/angular/src/app/utils/messages.ts
- client/wfprev-war/src/main/angular/src/app/utils/tools.ts
Call PUT in project detail page, populate the forms accordingly
> Update project hookup (#403)

- db/scripts/01_00_08/00/dml/app_wf1_prev.dml.plan_fiscal_status_code_update.sql
Data fix for plan_fiscal_status_code update
> WFPREV-238

- README.md
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/styles.scss
disable Cancel button when form has not been touched. 
throw snackbar error when lat,long is invalid before making api call.
fix overlap issue of map and input field
update the unit tests.
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-255
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-258
> WFPREV-255 WFPREV-258. Edit page UI changes and tests updates

- README.md
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/styles.scss
disable Cancel button when form has not been touched.
throw snackbar error when lat,long is invalid before making api call.
fix overlap issue of map and input field
update the unit tests.
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-255
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-258
> WFPREV-255 WFPREV-258. Edit page UI changes and tests updates (#422)

- db/app_wf1_prev-changelog.json
- db/scripts/01_00_12/00/ddl/WFPREV.alter_project_plan_fiscal.sql
liquibase action to add a column into project_plan_fiscals table
> Add funding_source_guid into project_plan_fiscals table

- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/fiscal-year-projects/fiscal-year-projects.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.ts
- client/wfprev-war/src/main/angular/src/app/utils/messages.ts
Multiple New Fiscal year should not be created
Warning message should be displayed when user deletes New Fiscal Year (no GUID)
Fiscal status validate as a required field
Number fields accept only positive values
> wfprev 297 298 299 300 (#495)

- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/fiscal-year-projects/fiscal-year-projects.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
Adding a checkbox, Change the readonly comment field to textarea. Change some layouts
> update on activity section layout

- db/app_wf1_prev-changelog.json
- db/scripts/01_00_15/00/ddl/app_wf1_prev.ddl.alter_audit_table_triggers.sql
- db/scripts/01_00_15/00/ddl/app_wf1_prev.ddl.modify_project_boundary.sql
Change location_geometry type from polygon to point
> WFPREV-360

- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.html
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.ts
Dynamically set BC park region field mandatory
> wfprev-287

- .github/workflows/client-build.yml
- .github/workflows/terragrunt-deploy.yml
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.html
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.scss
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.ts
- client/wfprev-war/src/main/angular/src/app/services/code-table-services.ts
- client/wfprev-war/src/main/angular/src/assets/data/appConfig.json
- client/wfprev-war/src/main/angular/src/assets/data/appConfig.local.json
- terraform/ecs.tf
- terraform/terragrunt.hcl
- terraform/variables.tf
add project type to create project screen, add fire centre to create project screen and edit screen
> Wfprev 353

- client/wfprev-war/src/main/angular/src/app/components/shared-layout/app-header/app-header.component.scss
- client/wfprev-war/src/main/angular/src/app/components/shared-layout/app-header/app-header.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/shared-layout/app-header/app-header.component.ts
- client/wfprev-war/src/main/angular/src/app/services/token.service.spec.ts
- client/wfprev-war/src/main/angular/src/app/services/token.service.ts
- client/wfprev-war/src/main/angular/src/assets/data/appConfig.json
- client/wfprev-war/src/main/angular/src/assets/data/appConfig.local.json
display idir name in header. Change wfnews to wfprev client id
> wfprev-363 

- client/wfprev-war/src/main/angular/src/app/components/add-attachment/add-attachment.component.html
- client/wfprev-war/src/main/angular/src/app/components/add-attachment/add-attachment.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/add-attachment/add-attachment.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-files/project-files.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-files/project-files.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-files/project-files.component.ts
I understand that we may need to update our liquibase to add 2 more attahcment content type code. So these part of tcode may need update too once the db script is change.
> add prescription file to acitivity (#606)

- client/wfprev-war/src/main/angular/src/app/components/edit-project/fiscal-map/fiscal-map.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-431
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-434
> fix wfprev-431 and wfprev-434 (#611)

- db/app_wf1_prev-changelog.json
- db/scripts/01_00_17/00/dml/app_wf1_prev.dml.load_activity_category_code.sql
Add missing Acitivity Category Codes
> WFPREV-449

- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.html
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.ts
- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.scss
> UI adjustment on search fitler, order fiscal card by year

- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.html
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.scss
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.ts
> dont wrap the title, but show ellipsis for fiscal name if it is too long (#651)

- client/wfprev-war/src/main/angular/src/app/app.component.scss
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.html
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.scss
- client/wfprev-war/src/main/angular/src/app/components/map/map.component.scss
- client/wfprev-war/src/main/angular/src/app/components/resizable-panel/resizable-panel.component.html
- client/wfprev-war/src/main/angular/src/app/components/resizable-panel/resizable-panel.component.scss
- client/wfprev-war/src/main/angular/src/app/components/resizable-panel/resizable-panel.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/resizable-panel/resizable-panel.component.ts
- client/wfprev-war/src/main/angular/src/styles.scss
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-459
desktop: ![image](https://github.com/user-attachments/assets/0295c1fc-c0a3-40c3-8bc4-a5d4b2f11e45)
laptop:
> Wfprev 459 adress the height issue, only use 100vh for the parent component, hide scrollbar for the app body

- client/wfprev-war/src/main/angular/src/app/components/map/map.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/map/map.component.ts
- client/wfprev-war/src/main/angular/src/app/services/map.service.spec.ts
- client/wfprev-war/src/main/angular/src/app/services/map.service.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-458
> Wfprev 458, fix map rendering issue 

- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.ts
- client/wfprev-war/src/main/angular/src/app/components/models.ts
- client/wfprev-war/src/main/angular/src/assets/dropdown-icon-white.svg
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-324
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-291
smaller screen
add new fiscal:
tooltip on long item:
> Wfprev-324, Wfprev-291 UI Updates: Fiscal Details and add proposal type dropdown as mandatory field, fix double scroll bar in fiscal tab

- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/data/assemblers/ProjectResourceAssembler.java
Remove Select as option for required field
Set select as default dropdown for non-required fields when they are null
Allow secondaryObjectiveCode and tertiaryObjectiveCode to be null on update
Fix lat/long Save button styling
> WFPREV-477,478 Fix UI bugs

- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
> wfprev:493 currency related fields have placeholder: $ 0.00

- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.html
- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.ts
- Unselecting "All" unchecks all individual options.
- If "All" is selected and a user unchecks any individual option, "All" should automatically be unchecked.
- If a user manually checks every individual option one by one, "All" should automatically become checked.
> wfprev-454 , add syncAllWithItemToggle method to handle ALL related behavior in filter

- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.html
- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.scss
Updated screenshots after addressing PR feedback:|
> WFPREV-482 Align filter dropdown and checkbox

- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.html
- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.scss
> WFPREV-482 Adjust checkbox alignment

- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.ts
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/controllers/ActivityBoundaryController.java
- server/wfprev-api/src/test/java/ca/bc/gov/nrs/wfprev/ActivityBoundaryControllerTest.java
> WFPREV-437 Update spatial added badge when spatial file is added to activity

- postman/Prevention.postman_collection.json
Add proposalTypeCode to projectFiscal
Remove dropped code tables
> Update Postman collection

- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
- client/wfprev-war/src/main/angular/src/app/components/shared/dropdown-button/dropdown-button.component.html
- client/wfprev-war/src/main/angular/src/app/components/shared/dropdown-button/dropdown-button.component.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-619
> wfprev-619, revert to "DRAFT" by unchecking endorsed or approval

- db/app_wf1_prev-changelog.json
- db/scripts/01_00_33/00/ddl/WFPREV.ddl.create.project_crx_vw.sql
- db/scripts/01_00_33/00/ddl/WFPREV.ddl.create.project_fuel_management_vw.sql
> WFPREV-674

- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.html
- client/wfprev-war/src/main/angular/src/app/components/search-filter/search-filter.component.ts
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/controllers/FeaturesController.java
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/data/params/FeatureQueryParams.java
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/services/FeaturesService.java
- server/wfprev-api/src/test/java/ca/bc/gov/nrs/wfprev/FeaturesControllerTest.java
- server/wfprev-api/src/test/java/ca/bc/gov/nrs/wfprev/services/FeaturesServiceTest.java
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-596
Will compotenize the filter dropdown in separte PR
> Wfprev 596 Add project type filter

- server/wfprev-api/pom.xml
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-132
Have to use <version>2.6.0</version>, use it is compatable with our springboot 3.2.0
Verified, the api spec will be accessible in: 
https://wfprev-dev.nrs.gov.bc.ca/wfprev-api/v3/api-docs
> adding openapi sepc

- client/wfprev-war/src/main/angular/src/app/components/shared-layout/app-header/app-header.component.stories.ts
- client/wfprev-war/src/main/angular/src/app/components/shared-layout/app-header/app-header.component.ts
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/services/FeaturesService.java
- server/wfprev-api/src/test/java/ca/bc/gov/nrs/wfprev/services/FeaturesServiceTest.java
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-666
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-445
> WFPREV-666 fiscal status turning to object

- client/wfprev-war/src/main/angular/src/app/components/confirmation-dialog/confirmation-dialog.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.ts
- client/wfprev-war/src/main/angular/src/app/utils/constants.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-634
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-655
disable in draft and show tooltip
disabled in Draft, Complete, Cancelled
> wfprev-634 disable endorsemnt/approval card when condition apply, wfprev-655

- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.html
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.ts
- client/wfprev-war/src/main/angular/src/app/components/evaluation-criteria-dialog/evaluation-criteria-dialog.component.html
- client/wfprev-war/src/main/angular/src/app/components/evaluation-criteria-dialog/evaluation-criteria-dialog.component.ts
- client/wfprev-war/src/main/angular/src/app/components/shared/textarea/textarea.component.html
- client/wfprev-war/src/main/angular/src/app/components/shared/textarea/textarea.component.scss
- client/wfprev-war/src/main/angular/src/app/components/shared/textarea/textarea.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/shared/textarea/textarea.component.ts
- client/wfprev-war/src/main/angular/src/app/utils/constants.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-628
Resue the same component for all text area
> wfprev-628 character count

- client/wfprev-war/src/main/angular/src/app/components/edit-project/activities/activities.component.scss
- client/wfprev-war/src/main/angular/src/app/components/edit-project/endorsement-approval/endorsement-approval.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/evaluation-criteria/evaluation-criteria.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.ts
- client/wfprev-war/src/main/angular/src/app/components/list-panel/projects-list/projects-list.component.html
- client/wfprev-war/src/main/angular/src/app/components/shared/dropdown-button/dropdown-button.component.html
- client/wfprev-war/src/main/angular/src/app/components/shared/input-field/input-field.component.html
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-513?
also fix the data range cutting off issue
> wfprev-513. clean up console error and warnings

- client/wfprev-war/src/main/angular/src/app/components/map/map.component.scss
- client/wfprev-war/src/main/angular/src/app/components/map/map.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/map/map.component.ts
- client/wfprev-war/src/main/angular/src/app/components/models.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/index.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/fire-perimeters.config.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/index.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/legacy-fuel-treatments.config.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/ministry-of-forests-districts.config.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/ministry-of-forests-regions.config.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/risk-reduction-projects-activities.config.ts
- client/wfprev-war/src/main/angular/src/app/services/map-config.service/layers/wildfire-org-unit-fire-centre.ts
- client/wfprev-war/src/main/angular/src/app/utils/constants.ts
Add 2 more layers, 1 from geoserver, 1 from openmaps.
Fit to BC on map loading.
Refresh layer on zoom,
Adjust layer panel styling.
identify:
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-747
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-779
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-780
> Add GeoServer Fuel Treatment layer, Add filtered WMS RESULTS Fuel Treatments layer

- client/wfprev-war/src/main/angular/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/edit-project.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-fiscals/project-fiscals.component.ts
- client/wfprev-war/src/main/angular/src/app/services/project-services.spec.ts
- client/wfprev-war/src/main/angular/src/app/services/project-services.ts
- client/wfprev-war/src/main/angular/src/app/utils/constants.ts
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-671
Delete EC Summary on chaning the project type.
If project has fiscal with status falls into " prepared/in progress/complete/cancelled ", disable the project type
> Handle Impact of Project Type Change on Evaluation Criteria Scores

- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.html
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/create-new-project-dialog/create-new-project-dialog.component.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.html
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.spec.ts
- client/wfprev-war/src/main/angular/src/app/components/edit-project/project-details/project-details.component.ts
- client/wfprev-war/src/main/angular/src/app/components/shared/input-field/input-field.component.html
- client/wfprev-war/src/main/angular/src/app/utils/constants.ts
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/data/repositories/ProjectRepository.java
- server/wfprev-api/src/main/java/ca/bc/gov/nrs/wfprev/services/ProjectService.java
- server/wfprev-api/src/test/java/ca/bc/gov/nrs/wfprev/services/ProjectServiceTest.java
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-694
https://apps.nrs.gov.bc.ca/int/jira/browse/WFPREV-699
> API: Project Name Uniqueness - Letter Casing,  UI: Project rename validation for duplicate record

- client/wfprev-war/src/main/angular/src/app/components/shared/download-button/download-button.component.scss
> WFPREV-782 Fill download button on hover
